### ISSUE TITLE
RLE decoding problems

### ISSUE THREAD

**Issue by PunkHaz4rd** [chafey/cornerstoneWADOImageLoader#103] opened 2017-07-11 09:22 UTC
Hello,
I'm currently working on a viewer and I stumbled on a problem with multiple sets of RLE DICOMs.

http://imgur.com/a/HhvXe

On the first image, you can see the image in JPEG given as a preview from the server.
The second one is the DICOM loaded with WADOImageLoader.

I anonymized the images myself because some infos are embedded in the pixel data, so sorry about that.
Though you can clearly see my problem on the DICOM, that there is a green overlay that shouldn't be here.

**Comment by PunkHaz4rd** [comment] 2017-07-11 09:26
By the way our images seems to have their encodedImage field as true.

**Comment by swederik** [comment] 2017-07-11 10:19
Thanks for the report!

**Comment by philem35** [comment] 2017-08-01 07:47
Hi swederik,
please find attached a data sample  illustrating the issue.
[issue.zip](https://github.com/chafey/cornerstoneWADOImageLoader/files/1189841/issue.zip)
You will be able to reproduce weird rendering.
The issue seems to be on RLE YBR decoding. It's decoded like a RGB image, while it's encoded by range. 
Regards
Philippe

**Comment by fbonnet-creative** [comment] 2017-08-09 10:17
The following pull request should fix the issue. It works with all images in the issue.zip file posted above by Philippe, I've also tested it with success on a series of images with the same decoding problem.

https://github.com/chafey/cornerstoneWADOImageLoader/pull/114

**Comment by swederik** [comment] 2017-10-30 08:35
Yep looks like @fbonnet-creative has fixed this issue, so I'll close it now. Thanks @fbonnet-creative!

**Closed by swederik** 2017-10-30 08:35 UTC
Labels: bug
