### ISSUE TITLE
DICOM image appearing very bright

### ISSUE THREAD

**Issue by RowanReid** [chafey/cornerstoneWADOImageLoader#36] opened 2016-04-08 10:58 UTC
I am not sure if I should be posting this issue here or in the https://github.com/chafey/dicomParser project.  Apologies if this is in the wrong place.

The DICOM file linked to at the bottom of this message is appearing very bright when viewed through Cornerstone, including via the online WADOImageLoader example here: http://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

When viewed any desktop DICOM viewer, like MicroDicom, it is displayed normally.

The DICOM file is 29mb and may be downloaded here: https://www.dropbox.com/s/qbf0i3x50bkz1tp/CR000000.dcm?dl=0

**Comment by chafey** [comment] 2016-04-08 11:22
This is the correct place for this issue.  The problem is with the VOI LUT - the LUT Descriptor x00283002 is invalid.  Since the LUT Descriptor is invalid, the LUT Is incorrect.  CornerstoneWADOImageLoader should detect this invalid LUT Descriptor and not create the VOI LUT.  Many vendors incorrectly implemented VOI LUT initially and special vendor specific workaround logic is required to display them properly.

**Comment by chafey** [comment] 2016-04-08 11:54
Oops - I might be wrong about the LUT Descriptor being invalid - there is a bug in the dicom dump utility and I didn't see elements two and three of the LUT descriptor.  Let me look into this more...

**Comment by RowanReid** [comment] 2016-04-08 11:59
Thanks Chris, appreciated!

**Comment by chafey** [comment] 2016-04-08 12:03
There is a bug in the LUT code, I will need to update cornerstone and cornerstoneWADOImageLoader to fix it.  Thanks for raising this issue!

**Comment by RowanReid** [comment] 2016-04-08 12:04
No problem! Great Stuff!

**Comment by chafey** [comment] 2016-04-08 12:19
Bad news - cornerstone is displaying the image as per the DICOM Standard, this specific vendor has a bug with how it produced the actual LUT data.  You can read more about this specific issue here: https://groups.google.com/forum/#!searchin/comp.protocols.dicom/VOI$20LUT/comp.protocols.dicom/agM0RIAqNfw/jkbBNR6aCg8J

**Comment by RowanReid** [comment] 2016-04-08 12:52
Ouch!  Ok thanks very much for looking into this, let me think on a way forward!

**Comment by chafey** [comment] 2016-04-08 13:02
We may want to add a callback mechanism to cornerstoneWADOImageLoader so bad LUT data like this can be "fixed" application side.  I don't want to add vendor specific workaround logic to cornerstone.  If you want to do this work and submit a PR, I would be happy to provide design input

**Comment by chafey** [comment] 2016-05-04 03:03
closing - added a callback to version 0.10.0 that allows callers to hook image creation and provide vendor specific workarounds

**Closed by chafey** 2016-05-04 03:03 UTC

**Comment by RowanReid** [comment] 2016-05-04 04:38
Thank you - very much appreciated!
